In [46]:
import pandas as pd
import numpy as np

In [25]:
data = pd.read_excel("../data/raw/Telco_customer_churn.xlsx")

In [26]:
data

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No,0,45,5306,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,One year,Yes,Mailed check,84.80,1990.5,No,0,59,2140,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,71,5560,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,38,5097,NaN

In [27]:
data.shape

(7043, 33)

In [28]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 2.9+ MB

In [29]:
missing_data = data.isnull().sum()
missing_data

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [30]:
data.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [31]:
data.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='str')

In [32]:
data.columns = data.columns.str.strip().str.lower().str.replace(" ","_")

In [33]:
data.columns

Index(['customerid', 'count', 'country', 'state', 'city', 'zip_code',
       'lat_long', 'latitude', 'longitude', 'gender', 'senior_citizen',
       'partner', 'dependents', 'tenure_months', 'phone_service',
       'multiple_lines', 'internet_service', 'online_security',
       'online_backup', 'device_protection', 'tech_support', 'streaming_tv',
       'streaming_movies', 'contract', 'paperless_billing', 'payment_method',
       'monthly_charges', 'total_charges', 'churn_label', 'churn_value',
       'churn_score', 'cltv', 'churn_reason'],
      dtype='str')

In [34]:
data.nunique()

customerid           7043
count                   1
country                 1
state                   1
city                 1129
zip_code             1652
lat_long             1652
latitude             1652
longitude            1651
gender                  2
senior_citizen          2
partner                 2
dependents              2
tenure_months          73
phone_service           2
multiple_lines          3
internet_service        3
online_security         3
online_backup           3
device_protection       3
tech_support            3
streaming_tv            3
streaming_movies        3
contract                3
paperless_billing       2
payment_method          4
monthly_charges      1585
total_charges        6531
churn_label             2
churn_value             2
churn_score            85
cltv                 3438
churn_reason           20
dtype: int64

In [35]:
for col in data:
    print(f"{col} \n", data[col].unique())
    print()

customerid
 <ArrowStringArray>
['3668-QPYBK', '9237-HQITU', '9305-CDSKC', '7892-POOKP', '0280-XJGEX',
 '4190-MFLUW', '8779-QRDMV', '1066-JKSGK', '6467-CHFZW', '8665-UTDHZ',
 ...
 '0871-OPBXW', '3605-JISKB', '9767-FFLEM', '8456-QDAVC', '7750-EYXWZ',
 '2569-WGERO', '6840-RESVB', '2234-XADUH', '4801-JZAZL', '3186-AJIEK']
Length: 7043, dtype: str

count
 [1]

country
 <ArrowStringArray>
['United States']
Length: 1, dtype: str

state
 <ArrowStringArray>
['California']
Length: 1, dtype: str

city
 <ArrowStringArray>
[    'Los Angeles',   'Beverly Hills', 'Huntington Park',         'Lynwood',
  'Marina Del Rey',       'Inglewood',    'Santa Monica',        'Torrance',
        'Whittier',        'La Habra',
 ...
      'Janesville',      'Litchfield',        'Loyalton',        'Madeline',
    'Markleeville',         'Milford',         'Calpine',        'Standish',
        'Tulelake',  'Olympic Valley']
Length: 1129, dtype: str

zip_code
 [90003 90005 90006 ... 96128 96134 96146]

lat_long
 <ArrowStringArray>
['33.964131, -118.272783',  '34.059281, -118.30742', '34.048013, -118.293953',
 '34.062125, -118.315709', '34.039224, -118.266293', '34.066367, -118.309868',
  '34.02381, -118.156582', '34.066303, -118.435479', '34.099869, -118.326843',
 '34.089953, -118.294824',
 ...
 '40.294034, -120.512622', '40.507272, -120.338228', '39.637471, -120.226338',
 '41.042003, -120.506086',  '38.735789, -119.85798', '40.181279, -120.392967',
 '39.672813, -120.456699', '40.346634, -120.386422', '41.813521, -121.492666',
 '39.191797, -120.212401']
Length: 1652, dtype: str

latitude
 [33.964131 34.059281 34.048013 ... 40.346634 41.813521 39.191797]

longitude
 [-118.272783 -118.30742  -118.293953 ... -120.386422 -121.492666
 -120.212401]

gender
 <ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

senior_citizen
 <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

partner
 <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

dependents
 <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

tenure_months
 [ 2  8 28 49 10  1 47 17  5 34 11 15 18  9  7 12 25 68 55 37  3 27 20  4
 58 53 13  6 19 59 16 52 24 32 38 54 43 63 21 69 22 61 60 48 40 23 39 35
 56 65 33 30 45 46 62 70 50 44 71 26 14 41 66 64 29 42 67 51 31 57 36 72
  0]

phone_service
 <ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

multiple_lines
 <ArrowStringArray>
['No', 'Yes', 'No phone service']
Length: 3, dtype: str

internet_service
 <ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

online_security
 <ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

online_backup
 <ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

device_protection
 <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

tech_support
 <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

streaming_tv
 <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

streaming_movies
 <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

contract
 <ArrowStringArray>
['Month-to-month', 'Two year', 'One year']
Length: 3, dtype: str

paperless_billing
 <ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

payment_method
 <ArrowStringArray>
[             'Mailed check',          'Electronic check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

monthly_charges
 [ 53.85  70.7   99.65 ... 108.35  63.1   78.7 ]

total_charges
 [108.15 151.65 820.5 ... 7362.9 346.45 6844.5]

churn_label
 <ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

churn_value
 [1 0]

churn_score
 [ 86  67  84  89  78 100  92  77  97  74  66  65  70  90  82  69  81  96
  87  88  75  76  95  99  80  73  94  83  98  71  85  68  91  93  72  79
  27  61  43  51  58  39  35  57  53  21  38  40  41  22  25  64  49  62
  52  59  29  33  20  30  26  54  56  55  28  37   9  60  24  63  23  47
  32   8  46  42  48  36  34   7  50  44  31   5  45]

cltv
 [3239 2701 5372 ... 2770 4645 5553]

churn_reason
 <ArrowStringArray>
[             'Competitor made better offer',
                                     'Moved',
             'Competitor had better devices',
 'Competitor offered higher download speeds',
              'Competitor offered more data',
                            'Price too high',
                   'Product dissatisfaction',
                   'Service dissatisfaction',
           'Lack of self-service on Website',
                       'Network reliability',
                 'Limited range of services',
  'Lack of affordable download/upload speed',
                     'Long distance charges',
                        'Extra data charges',
                                'Don't know',
          'Poor expertise of online support',
           'Poor expertise of phone support',
              'Attitude of service provider',
                'Attitude of support person',
                                  'Deceased',
                                         nan]
Length: 21, dtype: str

In [36]:
data.drop(columns=["customerid", "count", "country", "state", "lat_long"], inplace=True)

In [37]:
cols_to_replace = ["multiple_lines", "online_security", "online_backup",
                   "device_protection", "tech_support", "streaming_tv", "streaming_movies"]

for col in cols_to_replace:
    data[col] = data[col].replace({"No internet service": "No", "No phone service": "No"})

In [38]:
for cols in ["multiple_lines", "online_security", "online_backup",
                   "device_protection", "tech_support", "streaming_tv", "streaming_movies"]:
    print(f"{cols} \n", data[cols].unique())
    print()

multiple_lines
 <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

online_security
 <ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

online_backup
 <ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

device_protection
 <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

tech_support
 <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

streaming_tv
 <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

streaming_movies
 <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

In [39]:
data.drop(columns=["churn_label"], inplace=True)

In [40]:
data["total_charges"] = pd.to_numeric(data["total_charges"], errors="coerce")
data["total_charges"].isnull().sum()

np.int64(11)

In [41]:
data[np.isnan(data["total_charges"])]

,city,zip_code,latitude,longitude,gender,senior_citizen,partner,dependents,tenure_months,phone_service,...,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn_value,churn_score,cltv,churn_reason
2234,San Bernardino,92408,34.084909,-117.258107,Female,No,Yes,No,0,No,...,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,0,36,2578,NaN
2438,Independence,93526,36.869584,-118.189241,Male,No,No,No,0,Yes,...,No,Two year,No,Mailed check,20.25,NaN,0,68,5504,NaN
2568,San Mateo,94401,37.590421,-122.306467,Female,No,Yes,No,0,Yes,...,Yes,Two year,No,Mailed check,80.85,NaN,0,45,2048,NaN
2667,Cupertino,95014,37.306612,-122.080621,Male,No,Yes,Yes,0,Yes,...,No,Two year,No,Mailed check,25.75,NaN,0,48,4950,NaN
2856,Redcrest,95569,40.363446,-123.835041,Female,No,Yes,No,0,No,...,No,Two year,No,Credit card (automatic),56.05,NaN,0,30,4740,NaN
4331,Los Angeles,90029,34.089953,-118.294824,Male,No,Yes,Yes,0,Yes,...,No,Two year,No,Mailed check,19.85,NaN,0,53,2019,NaN
4687,Sun City,92585,33.739412,-117.173334,Male,No,Yes,Yes,0,Yes,...,No,Two year,No,Mailed check,25.35,NaN,0,49,2299,NaN
5104,Ben Lomond,95005,37.078873,-122.090386,Female,No,Yes,Yes,0,Yes,...,No,Two year,No,Mailed check,20.00,NaN,0,27,3763,NaN
5719,La Verne,91750,34.144703,-117.770299,Male,No,Yes,Yes,0,Yes,...,No,One year,Yes,Mailed check,19.70,NaN,0,69,4890,NaN
6772,Bell,90201,33.970343,-118.171368,Female,No,Yes,Yes,0,Yes,...,No,Two year,No,Mailed check,73.35,NaN,0,44,2342,NaN
6840,Wilmington,90744,33.782068,-118.262263,Male,No,No,Yes,0,Yes,...,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,0,65,5188,NaN

In [42]:
data.fillna(data["total_charges"].mean())

,city,zip_code,latitude,longitude,gender,senior_citizen,partner,dependents,tenure_months,phone_service,...,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn_value,churn_score,cltv,churn_reason
0,Los Angeles,90003,33.964131,-118.272783,Male,No,No,No,2,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,86,3239,Competitor made better offer
1,Los Angeles,90005,34.059281,-118.307420,Female,No,No,Yes,2,Yes,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,67,2701,Moved
2,Los Angeles,90006,34.048013,-118.293953,Female,No,No,Yes,8,Yes,...,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,1,86,5372,Moved
3,Los Angeles,90010,34.062125,-118.315709,Female,No,Yes,Yes,28,Yes,...,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1,84,5003,Moved
4,Los Angeles,90015,34.039224,-118.266293,Male,No,No,Yes,49,Yes,...,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,1,89,5340,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Landers,92285,34.341737,-116.539416,Female,No,No,No,72,Yes,...,No,Two year,Yes,Bank transfer (automatic),21.15,1419.40,0,45,5306,2283.300441
7039,Adelanto,92301,34.667815,-117.536183,Male,No,Yes,Yes,24,Yes,...,Yes,One year,Yes,Mailed check,84.80,1990.50,0,59,2140,2283.300441
7040,Amboy,92304,34.559882,-115.637164,Female,No,Yes,Yes,72,Yes,...,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,0,71,5560,2283.300441
7041,Angelus Oaks,92305,34.167800,-116.864330,Female,No,Yes,Yes,11,No,...,No,Month-to-month,Yes,Electronic check,29.60,346.45,0,59,2793,2283.300441
7042,Apple Valley,92308,34.424926,-117.184503,Male,No,No,No,66,Yes,...,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,0,38,5097,2283.300441

In [43]:
data["churn_reason"].value_counts(dropna=False)

churn_reason
NaN                                          5174
Attitude of support person                    192
Competitor offered higher download speeds     189
Competitor offered more data                  162
Don't know                                    154
Competitor made better offer                  140
Attitude of service provider                  135
Competitor had better devices                 130
Network reliability                           103
Product dissatisfaction                       102
Price too high                                 98
Service dissatisfaction                        89
Lack of self-service on Website                88
Extra data charges                             57
Moved                                          53
Limited range of services                      44
Lack of affordable download/upload speed       44
Long distance charges                          44
Poor expertise of phone support                20
Poor expertise of online support               19
Deceased                                        6
Name: count, dtype: int64

In [44]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   city               7043 non-null   str
 1   zip_code           7043 non-null   int64
 2   latitude           7043 non-null   float64
 3   longitude          7043 non-null   float64
 4   gender             7043 non-null   str
 5   senior_citizen     7043 non-null   str
 6   partner            7043 non-null   str
 7   dependents         7043 non-null   str
 8   tenure_months      7043 non-null   int64
 9   phone_service      7043 non-null   str
 10  multiple_lines     7043 non-null   str
 11  internet_service   7043 non-null   str
 12  online_security    7043 non-null   str
 13  online_backup      7043 non-null   str
 14  device_protection  7043 non-null   str
 15  tech_support       7043 non-null   str
 16  streaming_tv       7043 non-null   str
 17  streaming_movies   7043 non-null   str
 18  contract           7043 non-null   str
 19  paperless_billing  7043 non-null   str
 20  payment_method     7043 non-null   str
 21  monthly_charges    7043 non-null   float64
 22  total_charges      7032 non-null   float64
 23  churn_value        7043 non-null   int64
 24  churn_score        7043 non-null   int64
 25  cltv               7043 non-null   int64
 26  churn_reason       1869 non-null   str
dtypes: float64(4), int64(5), str(18)
memory usage: 2.0 MB

In [45]:
data.to_parquet("../data/clean/cleaned_data.parquet", index=False)
data.to_csv("../data/clean/cleaned_data.csv", index=False)