In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("../data/clean/cleaned_featureng_data.csv")

In [4]:
data

,customerid,city,zip_code,latitude,longitude,gender,senior_citizen,partner,dependents,tenure_months,...,churn_reason,avg_monthly_charge,charge_vs_avg,payment_ratio,total_services,cost_per_service,high_risk,engagement_score,tenure_x_contract,charge_x_risk
0,3668-QPYBK,Los Angeles,90003,33.964131,-118.272783,Male,No,No,No,2,...,Competitor made better offer,54.075000,-10.911692,1.004178,3,17.950000,2,0.456349,0,107.70
1,9237-HQITU,Los Angeles,90005,34.059281,-118.307420,Female,No,No,Yes,2,...,Moved,75.825000,5.938308,1.072489,1,70.700000,3,1.170635,0,212.10
2,9305-CDSKC,Los Angeles,90006,34.048013,-118.293953,Female,No,No,Yes,8,...,Moved,102.562500,34.888308,1.029227,4,24.912500,3,1.682540,0,298.95
3,7892-POOKP,Los Angeles,90010,34.062125,-118.315709,Female,No,Yes,Yes,28,...,Moved,108.787500,40.038308,1.038049,5,20.960000,3,3.103175,0,314.40
4,0280-XJGEX,Los Angeles,90015,34.039224,-118.266293,Male,No,No,Yes,49,...,Competitor had better devices,102.781633,38.938308,0.991144,5,20.740000,2,2.394841,0,207.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,Landers,92285,34.341737,-116.539416,Female,No,No,No,72,...,NaN,19.713889,-43.611692,0.932099,1,21.150000,1,3.142857,144,21.15
7039,6840-RESVB,Adelanto,92301,34.667815,-117.536183,Male,No,Yes,Yes,24,...,NaN,82.937500,20.038308,0.978037,6,14.133333,1,4.190476,24,84.80
7040,2234-XADUH,Amboy,92304,34.559882,-115.637164,Female,No,Yes,Yes,72,...,NaN,102.262500,38.438308,0.990916,5,20.640000,1,4.714286,72,103.20
7041,4801-JZAZL,Angelus Oaks,92305,34.167800,-116.864330,Female,No,Yes,Yes,11,...,NaN,31.495455,-35.161692,1.064036,1,29.600000,3,2.295635,0,88.80
7042,3186-AJIEK,Apple Valley,92308,34.424926,-117.184503,Male,No,No,No,66,...,NaN,103.704545,40.888308,0.981586,6,17.608333,1,3.773810,132,105.65

In [5]:
data.shape

(7043, 37)

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 37 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerid          7043 non-null   str
 1   city                7043 non-null   str
 2   zip_code            7043 non-null   int64
 3   latitude            7043 non-null   float64
 4   longitude           7043 non-null   float64
 5   gender              7043 non-null   str
 6   senior_citizen      7043 non-null   str
 7   partner             7043 non-null   str
 8   dependents          7043 non-null   str
 9   tenure_months       7043 non-null   int64
 10  phone_service       7043 non-null   str
 11  multiple_lines      7043 non-null   str
 12  internet_service    7043 non-null   str
 13  online_security     7043 non-null   str
 14  online_backup       7043 non-null   str
 15  device_protection   7043 non-null   str
 16  tech_support        7043 non-null   str
 17  streaming_tv        7043 non-null   str
 18  streaming_movies    7043 non-null   str
 19  contract            7043 non-null   str
 20  paperless_billing   7043 non-null   str
 21  payment_method      7043 non-null   str
 22  monthly_charges     7043 non-null   float64
 23  total_charges       7043 non-null   float64
 24  churn_value         7043 non-null   int64
 25  churn_score         7043 non-null   int64
 26  cltv                7043 non-null   int64
 27  churn_reason        1869 non-null   str
 28  avg_monthly_charge  7043 non-null   float64
 29  charge_vs_avg       7043 non-null   float64
 30  payment_ratio       7043 non-null   float64
 31  total_services      7043 non-null   int64
 32  cost_per_service    7043 non-null   float64
 33  high_risk           7043 non-null   int64
 34  engagement_score    7043 non-null   float64
 35  tenure_x_contract   7043 non-null   int64
 36  charge_x_risk       7043 non-null   float64
dtypes: float64(10), int64(8), str(19)
memory usage: 2.6 MB

In [7]:
missing_data = data.isnull().sum()
missing_data

customerid               0
city                     0
zip_code                 0
latitude                 0
longitude                0
gender                   0
senior_citizen           0
partner                  0
dependents               0
tenure_months            0
phone_service            0
multiple_lines           0
internet_service         0
online_security          0
online_backup            0
device_protection        0
tech_support             0
streaming_tv             0
streaming_movies         0
contract                 0
paperless_billing        0
payment_method           0
monthly_charges          0
total_charges            0
churn_value              0
churn_score              0
cltv                     0
churn_reason          5174
avg_monthly_charge       0
charge_vs_avg            0
payment_ratio            0
total_services           0
cost_per_service         0
high_risk                0
engagement_score         0
tenure_x_contract        0
charge_x_risk            0
dtype: int64

In [11]:
data[data.duplicated()]

Empty DataFrame
Columns: [customerid, city, zip_code, latitude, longitude, gender, senior_citizen, partner, dependents, tenure_months, phone_service, multiple_lines, internet_service, online_security, online_backup, device_protection, tech_support, streaming_tv, streaming_movies, contract, paperless_billing, payment_method, monthly_charges, total_charges, churn_value, churn_score, cltv, churn_reason, avg_monthly_charge, charge_vs_avg, payment_ratio, total_services, cost_per_service, high_risk, engagement_score, tenure_x_contract, charge_x_risk]
Index: []

[0 rows x 37 columns]

In [8]:
data.describe()

,zip_code,latitude,longitude,tenure_months,monthly_charges,total_charges,churn_value,churn_score,cltv,avg_monthly_charge,charge_vs_avg,payment_ratio,total_services,cost_per_service,high_risk,engagement_score,tenure_x_contract,charge_x_risk
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7.043000e+03,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,93521.964646,36.282441,-119.798880,32.371149,64.761692,2279.734304,0.265370,58.699418,4400.295755,64.762906,-2.066153e-15,1.000274,2.941076,26.015044,1.478205,2.274268,36.101661,105.698133
std,1865.794555,2.455723,2.157889,24.559481,30.090047,2266.794470,0.441561,21.525131,1183.057152,30.189796,3.009005e+01,0.051119,1.843899,13.828951,1.023538,1.631936,50.598114,91.420271
min,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,0.000000,5.000000,2003.000000,13.775000,-4.651169e+01,0.689356,0.000000,10.416667,0.000000,0.013889,0.000000,0.000000
25%,92102.000000,34.030915,-121.815412,9.000000,35.500000,398.550000,0.000000,40.000000,3469.000000,35.935156,-2.926169e+01,0.979623,1.000000,18.400000,1.000000,0.746032,0.000000,20.300000
50%,93552.000000,36.391777,-119.730885,29.000000,70.350000,1394.550000,0.000000,61.000000,4527.000000,70.337500,5.588308e+00,1.000000,3.000000,20.880000,1.000000,2.071429,0.000000,89.850000
75%,95351.000000,38.224869,-118.043237,55.000000,89.850000,3786.600000,1.000000,75.000000,5380.500000,90.174158,2.508831e+01,1.019491,4.000000,28.150000,2.000000,3.529762,62.000000,173.200000
max,96161.000000,41.962127,-114.192901,72.000000,118.750000,8684.800000,1.000000,100.000000,6500.000000,121.400000,5.398831e+01,1.573454,7.000000,77.900000,3.000000,6.000000,144.000000,349.500000

In [9]:
data.columns

Index(['customerid', 'city', 'zip_code', 'latitude', 'longitude', 'gender',
       'senior_citizen', 'partner', 'dependents', 'tenure_months',
       'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'total_charges', 'churn_value',
       'churn_score', 'cltv', 'churn_reason', 'avg_monthly_charge',
       'charge_vs_avg', 'payment_ratio', 'total_services', 'cost_per_service',
       'high_risk', 'engagement_score', 'tenure_x_contract', 'charge_x_risk'],
      dtype='str')

In [16]:
data.drop(columns=["customerid", "city", "zip_code", "latitude", "longitude", "churn_score", "churn_reason"], inplace=True) #cltv

In [17]:
data.to_parquet("../data/clean/build_dataset.parquet", index=False)
data.to_csv("../data/clean/build_dataset.csv", index=False)