In [31]:
import pandas as pd
import numpy as np

In [32]:
data = pd.read_csv("../data/clean/cleaned_featureng_data.csv")

In [33]:
data

,customerid,city,zip_code,latitude,longitude,gender,senior_citizen,partner,dependents,tenure_months,...,payment_ratio,total_services,cost_per_service,high_risk,engagement_score,tenure_x_contract,charge_x_risk,log_total_charges,log_monthly_charges,log_cltv
0,3668-QPYBK,Los Angeles,90003,33.964131,-118.272783,Male,No,No,No,2,...,1.004178,3,17.950000,2,0.456349,0,107.70,4.692723,4.004602,8.083329
1,9237-HQITU,Los Angeles,90005,34.059281,-118.307420,Female,No,No,Yes,2,...,1.072489,1,70.700000,3,1.170635,0,212.10,5.028148,4.272491,7.901748
2,9305-CDSKC,Los Angeles,90006,34.048013,-118.293953,Female,No,No,Yes,8,...,1.029227,4,24.912500,3,1.682540,0,298.95,6.711132,4.611649,8.589142
3,7892-POOKP,Los Angeles,90010,34.062125,-118.315709,Female,No,Yes,Yes,28,...,1.038049,5,20.960000,3,3.103175,0,314.40,8.021929,4.661551,8.517993
4,0280-XJGEX,Los Angeles,90015,34.039224,-118.266293,Male,No,No,Yes,49,...,0.991144,5,20.740000,2,2.394841,0,207.40,8.524626,4.651099,8.583168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,Landers,92285,34.341737,-116.539416,Female,No,No,No,72,...,0.932099,1,21.150000,1,3.142857,144,21.15,7.258694,3.097837,8.576782
7039,6840-RESVB,Adelanto,92301,34.667815,-117.536183,Male,No,Yes,Yes,24,...,0.978037,6,14.133333,1,4.190476,24,84.80,7.596643,4.452019,7.669028
7040,2234-XADUH,Amboy,92304,34.559882,-115.637164,Female,No,Yes,Yes,72,...,0.990916,5,20.640000,1,4.714286,72,103.20,8.904345,4.646312,8.623533
7041,4801-JZAZL,Angelus Oaks,92305,34.167800,-116.864330,Female,No,Yes,Yes,11,...,1.064036,1,29.600000,3,2.295635,0,88.80,5.850621,3.421000,7.935230
7042,3186-AJIEK,Apple Valley,92308,34.424926,-117.184503,Male,No,No,No,66,...,0.981586,6,17.608333,1,3.773810,132,105.65,8.831347,4.669552,8.536604

In [34]:
data.shape

(7043, 41)

In [35]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 41 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customerid           7043 non-null   str
 1   city                 7043 non-null   str
 2   zip_code             7043 non-null   int64
 3   latitude             7043 non-null   float64
 4   longitude            7043 non-null   float64
 5   gender               7043 non-null   str
 6   senior_citizen       7043 non-null   str
 7   partner              7043 non-null   str
 8   dependents           7043 non-null   str
 9   tenure_months        7043 non-null   int64
 10  phone_service        7043 non-null   str
 11  multiple_lines       7043 non-null   str
 12  internet_service     7043 non-null   str
 13  online_security      7043 non-null   str
 14  online_backup        7043 non-null   str
 15  device_protection    7043 non-null   str
 16  tech_support         7043 non-null   str
 17  streaming_tv         7043 non-null   str
 18  streaming_movies     7043 non-null   str
 19  contract             7043 non-null   str
 20  paperless_billing    7043 non-null   str
 21  payment_method       7043 non-null   str
 22  monthly_charges      7043 non-null   float64
 23  total_charges        7043 non-null   float64
 24  churn_value          7043 non-null   int64
 25  churn_score          7043 non-null   int64
 26  cltv                 7043 non-null   int64
 27  churn_reason         1869 non-null   str
 28  tenure_group         7043 non-null   str
 29  avg_monthly_charge   7043 non-null   float64
 30  charge_vs_avg        7043 non-null   float64
 31  payment_ratio        7043 non-null   float64
 32  total_services       7043 non-null   int64
 33  cost_per_service     7043 non-null   float64
 34  high_risk            7043 non-null   int64
 35  engagement_score     7043 non-null   float64
 36  tenure_x_contract    7043 non-null   int64
 37  charge_x_risk        7043 non-null   float64
 38  log_total_charges    7043 non-null   float64
 39  log_monthly_charges  7043 non-null   float64
 40  log_cltv             7043 non-null   float64
dtypes: float64(13), int64(8), str(20)
memory usage: 2.9 MB

In [36]:
missing_data = data.isnull().sum()
missing_data

customerid                0
city                      0
zip_code                  0
latitude                  0
longitude                 0
gender                    0
senior_citizen            0
partner                   0
dependents                0
tenure_months             0
phone_service             0
multiple_lines            0
internet_service          0
online_security           0
online_backup             0
device_protection         0
tech_support              0
streaming_tv              0
streaming_movies          0
contract                  0
paperless_billing         0
payment_method            0
monthly_charges           0
total_charges             0
churn_value               0
churn_score               0
cltv                      0
churn_reason           5174
tenure_group              0
avg_monthly_charge        0
charge_vs_avg             0
payment_ratio             0
total_services            0
cost_per_service          0
high_risk                 0
engagement_score          0
tenure_x_contract         0
charge_x_risk             0
log_total_charges         0
log_monthly_charges       0
log_cltv                  0
dtype: int64

In [37]:
data[data.duplicated()]

Empty DataFrame
Columns: [customerid, city, zip_code, latitude, longitude, gender, senior_citizen, partner, dependents, tenure_months, phone_service, multiple_lines, internet_service, online_security, online_backup, device_protection, tech_support, streaming_tv, streaming_movies, contract, paperless_billing, payment_method, monthly_charges, total_charges, churn_value, churn_score, cltv, churn_reason, tenure_group, avg_monthly_charge, charge_vs_avg, payment_ratio, total_services, cost_per_service, high_risk, engagement_score, tenure_x_contract, charge_x_risk, log_total_charges, log_monthly_charges, log_cltv]
Index: []

[0 rows x 41 columns]

In [38]:
data.describe()

,zip_code,latitude,longitude,tenure_months,monthly_charges,total_charges,churn_value,churn_score,cltv,avg_monthly_charge,...,payment_ratio,total_services,cost_per_service,high_risk,engagement_score,tenure_x_contract,charge_x_risk,log_total_charges,log_monthly_charges,log_cltv
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,...,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,93521.964646,36.282441,-119.798880,32.371149,64.761692,2279.734304,0.265370,58.699418,4400.295755,64.762906,...,1.000274,2.941076,26.015044,1.478205,2.274268,36.101661,105.698133,6.932543,4.043347,8.347937
std,1865.794555,2.455723,2.157889,24.559481,30.090047,2266.794470,0.441561,21.525131,1183.057152,30.189796,...,0.051119,1.843899,13.828951,1.023538,1.631936,50.598114,91.420271,1.569371,0.580288,0.300712
min,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,0.000000,5.000000,2003.000000,13.775000,...,0.689356,0.000000,10.416667,0.000000,0.013889,0.000000,0.000000,0.000000,2.957511,7.602900
25%,92102.000000,34.030915,-121.815412,9.000000,35.500000,398.550000,0.000000,40.000000,3469.000000,35.935156,...,0.979623,1.000000,18.400000,1.000000,0.746032,0.000000,20.300000,5.990339,3.597312,8.151910
50%,93552.000000,36.391777,-119.730885,29.000000,70.350000,1394.550000,0.000000,61.000000,4527.000000,70.337500,...,1.000000,3.000000,20.880000,1.000000,2.071429,0.000000,89.850000,7.241044,4.267597,8.418036
75%,95351.000000,38.224869,-118.043237,55.000000,89.850000,3786.600000,1.000000,75.000000,5380.500000,90.174158,...,1.019491,4.000000,28.150000,2.000000,3.529762,62.000000,173.200000,8.239488,4.509210,8.590722
max,96161.000000,41.962127,-114.192901,72.000000,118.750000,8684.800000,1.000000,100.000000,6500.000000,121.400000,...,1.573454,7.000000,77.900000,3.000000,6.000000,144.000000,349.500000,9.069445,4.785406,8.779711

In [39]:
data.columns

Index(['customerid', 'city', 'zip_code', 'latitude', 'longitude', 'gender',
       'senior_citizen', 'partner', 'dependents', 'tenure_months',
       'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'total_charges', 'churn_value',
       'churn_score', 'cltv', 'churn_reason', 'tenure_group',
       'avg_monthly_charge', 'charge_vs_avg', 'payment_ratio',
       'total_services', 'cost_per_service', 'high_risk', 'engagement_score',
       'tenure_x_contract', 'charge_x_risk', 'log_total_charges',
       'log_monthly_charges', 'log_cltv'],
      dtype='str')

In [40]:
data.drop(columns=["customerid", "city", "zip_code", "latitude", "longitude", "churn_score", "churn_reason"], inplace=True) #cltv

In [41]:
print(f"Final shape: {data.shape}")
print(data.columns.tolist())
print(data.dtypes)

Final shape: (7043, 34)
['gender', 'senior_citizen', 'partner', 'dependents', 'tenure_months', 'phone_service', 'multiple_lines', 'internet_service', 'online_security', 'online_backup', 'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing', 'payment_method', 'monthly_charges', 'total_charges', 'churn_value', 'cltv', 'tenure_group', 'avg_monthly_charge', 'charge_vs_avg', 'payment_ratio', 'total_services', 'cost_per_service', 'high_risk', 'engagement_score', 'tenure_x_contract', 'charge_x_risk', 'log_total_charges', 'log_monthly_charges', 'log_cltv']
gender                     str
senior_citizen             str
partner                    str
dependents                 str
tenure_months            int64
phone_service              str
multiple_lines             str
internet_service           str
online_security            str
online_backup              str
device_protection          str
tech_support               str
streaming_tv               str
streaming_movies           str
contract                   str
paperless_billing          str
payment_method             str
monthly_charges        float64
total_charges          float64
churn_value              int64
cltv                     int64
tenure_group               str
avg_monthly_charge     float64
charge_vs_avg          float64
payment_ratio          float64
total_services           int64
cost_per_service       float64
high_risk                int64
engagement_score       float64
tenure_x_contract        int64
charge_x_risk          float64
log_total_charges      float64
log_monthly_charges    float64
log_cltv               float64
dtype: object

In [42]:
data.to_parquet("../data/clean/build_dataset.parquet", index=False)
data.to_csv("../data/clean/build_dataset.csv", index=False)